

List<String> foodList=[
  'Hard tacos',
  'Huevos rancheros',
  'Stir fry',
  'Burritos',
  'Fajitas',
  'Quesadillas ',
  'Meatballs ',
  'Sloppy Joes',
  'Chicken and rice',
  'Pot roast ',
  'Crockpot salsa chicken',
  'Ribs',
  'Pulled BBQ chicken',
  'Twice-baked potatoes',
  'Chicken pot pie',
  'Homemade corn dogs',
  "Shepherd's pie",
  'Enchiladas',
  'Egg rolls',
  'Fried chicken',
  'Breaded chicken',
  'Chicken nuggets',
  'Chicken wings',
  'Cheesy bacon chicken',
  'Dijon chicken',
  'Chicken fingers',
  'Orange chicken',
  'Cilantro-lime chicken',
  'Lemon chicken',
  'Meatloaf',
  'Meatball subs',
  'Salmon',
  'Fish ‘n chips',
  'Crab cakes',
  'Fish tacos',
  'Smoked salmon bagel',
  'Minestrone soup',
  'Chicken noodle soup',
  'White chicken chili',
  'Tomato bisque',
  'Italian wedding soup',
  'Chicken enchilada/tortilla soup',
  'Cheeseburger soup',
  'Corn chowder',
  'French onion soup',
  'Jambalaya',
];